// status.enum.ts
export enum Status {
  OK = 'OK',
  ERROR = 'ERROR',
  CREATED = 'CREATED',
  BAD_REQUEST = 'BAD REQUEST',
  UNAUTHORIZED = 'AUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
}
